In [ ]:
print("hello")

hello


In [ ]:
def hello():
  print("hello how are you")

In [ ]:
hello()

hello how are you


# NUMPY

In [ ]:
import numpy as np


In [ ]:
arr = np.array([1,2,3,4,5.5])

In [ ]:
arr

array([1. , 2. , 3. , 4. , 5.5])

In [ ]:
a = np.array([1,2,3,"hello"])

In [ ]:
a

array(['1', '2', '3', 'hello'], dtype='<U21')

In [ ]:
# vectors

l = ([1,2,3],[4,5,6],[7,8,9])
l

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [ ]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

# random generation functions

In [ ]:
np.random.rand(5)

array([0.89985874, 0.20311582, 0.58312411, 0.52078639, 0.74517337])

In [ ]:
np.random.randn(10)

array([-1.31247407, -1.64268557,  0.23568383,  0.00674182, -1.43883026,
       -0.06380803,  0.17199315, -0.93128424, -0.02923902, -0.57399929])

In [ ]:
np.random.randn(10)

array([ 0.76167273,  0.05203449, -1.06060917, -0.36030042,  0.10926382,
       -1.14585359,  0.64846655,  0.61310353, -2.60419216,  0.85741955])

In [ ]:
np.random.randint(2)

1

In [ ]:
np.random.randint(10,20,10)

array([17, 18, 18, 12, 10, 15, 18, 15, 12, 10])

# ARRAY ATTRIBUTES


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[5,8,4]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [5, 8, 4]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(8)

In [ ]:
arr.sum()

np.int64(38)

In [ ]:
np.sum(arr,axis = 0)

array([10, 15, 13])

In [ ]:
np.sum(arr,axis = 1)

array([ 6, 15, 17])

In [ ]:
arr.mean()

np.float64(4.222222222222222)

In [ ]:
arr.std()

np.float64(1.9876159799998132)

In [ ]:
arr.argmax()

np.int64(7)

In [ ]:
arr.argmin()

np.int64(0)

In [ ]:
# reshaping and resizing

arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

INDEXING AND SLICING OF VECTORS


In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3]

np.int64(14)

In [ ]:
arr[1:5]

array([12, 13, 14, 15])

In [ ]:
arr[:5]

array([11, 12, 13, 14, 15])

In [ ]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3::2]

array([14, 16, 18, 20])

NUMPY INDEXING AND SLICING OF MATRIX


In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[3]

array([16, 17, 18, 19, 20])

In [ ]:
arr[0,0]

np.int64(1)

In [ ]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [ ]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

# BOOLEAN INDEXING



In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# **ARRAY OPERATIONS**


In [ ]:
# arithemetic operations


In [ ]:
a1 = np.array([1,2,3,5,8,2])
a2 = np.array([5,8,6,8,7,5])
a1

array([1, 2, 3, 5, 8, 2])

In [ ]:
a2

array([5, 8, 6, 8, 7, 5])

In [ ]:
a1 + a2

array([ 6, 10,  9, 13, 15,  7])

In [ ]:
a1 - a2

array([-4, -6, -3, -3,  1, -3])

In [ ]:
a1 * a2

array([ 5, 16, 18, 40, 56, 10])

In [ ]:
a1 / a2

array([0.2       , 0.25      , 0.5       , 0.625     , 1.14285714,
       0.4       ])

In [ ]:
a1 // a2

array([0, 0, 0, 0, 1, 0])

In [ ]:
a1 ** a2

array([      1,     256,     729,  390625, 2097152,      32])

BROADCASTING

In [ ]:
l = [10,20,30,40,50]
arr = np.array(l)

In [ ]:
arr+10

array([20, 30, 40, 50, 60])

In [ ]:
arr3 = np.arange(1,26).reshape(5,5)
arr3+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [ ]:
arr3*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

# DEEP AND SHALLOW **COPY**

In [ ]:
b = np.arange(1,21)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice = b[0:5]
slice * 10

array([10, 20, 30, 40, 50])

In [ ]:
slice = b[4:6] * 10
slice

array([50, 60])

In [ ]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a
b = a

In [ ]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b
a = b.copy()

In [ ]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[9,8]])


In [ ]:
mat1

array([[1, 2],
       [3, 4]])

In [ ]:
mat2

array([[5, 6],
       [9, 8]])

In [ ]:
mat1 * mat2

array([[ 5, 12],
       [27, 32]])

In [ ]:
mat1 @ mat2

array([[23, 22],
       [51, 50]])

In [ ]:
np.dot(mat1,mat2)

array([[23, 22],
       [51, 50]])

In [ ]:
mat1

array([[1, 2],
       [3, 4]])

In [ ]:
mat1.T

array([[1, 3],
       [2, 4]])

# **ARRAY MANIPULATION**

In [ ]:
a1 = np.array([1,2,3,5,8,2])
a2 = np.array([5,8,6,8,7,5])


In [ ]:
np.vstack((a1,a2))

array([[1, 2, 3, 5, 8, 2],
       [5, 8, 6, 8, 7, 5]])

In [ ]:
np.hstack((a1,a2))

array([1, 2, 3, 5, 8, 2, 5, 8, 6, 8, 7, 5])

In [ ]:
np.column_stack((a1,a2))

array([[1, 5],
       [2, 8],
       [3, 6],
       [5, 8],
       [8, 7],
       [2, 5]])

In [ ]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

# **EXERSISES**

In [ ]:
import numpy as np

s = np.array([
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9]
])

print(s)


[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [ ]:
b = np.sum(s,axis = 1)
b == 45


array([False, False, False, False, False, False, False, False, False])

In [ ]:
b = np.sum(s,axis = 1)
for i in b:
  if i == 45:
    print("sudoku is valid")
    break
else:
  print("sudoku is invalid")


sudoku is invalid


In [ ]:
s[0:3,0:3]

array([[5, 3, 0],
       [6, 0, 0],
       [0, 9, 8]])

In [ ]:
s[0:3,3:6]

array([[0, 7, 0],
       [1, 9, 5],
       [0, 0, 0]])

In [ ]:
s[0:3,6:9]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 6, 0]])

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n = (s[i:i+3,j:j+3])
    print(n.sum())

31
22
6
19
19
10
6
22
31


In [ ]:
import numpy as np

students = np.array([
    [18, 85, 90],
    [19, 78, 88],
    [17, 92, 95],
    [18, 74, 80],
    [20, 89, 91]
])

print(students)


[[18 85 90]
 [19 78 88]
 [17 92 95]
 [18 74 80]
 [20 89 91]]


In [ ]:
students.shape

(5, 3)

In [ ]:
np.mean(students[:,0])

np.float64(18.4)

In [ ]:
students[:,1]

array([85, 78, 92, 74, 89])

In [ ]:
np.max(students[:,2])

np.int64(95)

In [ ]:
students[students[:,1] > 90]

array([[17, 92, 95]])

In [ ]:
students[:,1] += 5
students

array([[18, 90, 90],
       [19, 83, 88],
       [17, 97, 95],
       [18, 79, 80],
       [20, 94, 91]])

In [ ]:
len(students[students[:,0] < 19])

3

In [ ]:
np.mean(students[:,1:],axis = 0)

array([88.6, 88.8])

In [ ]:
students[(students[:,1] >= 80) & (students[:,2] >= 80 )]

array([[18, 90, 90],
       [19, 83, 88],
       [17, 97, 95],
       [20, 94, 91]])

In [ ]:
students

array([[18, 90, 90],
       [19, 83, 88],
       [17, 97, 95],
       [18, 79, 80],
       [20, 94, 91]])

In [ ]:
students[:,2][students[:,2] < 85] = 0
students

array([[18, 90, 90],
       [19, 83, 88],
       [17, 97, 95],
       [18, 79,  0],
       [20, 94, 91]])